@baseUrl=http://localhost:8080
@token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQyMzc3NzUxLCJleHAiOjE3NDIzODEzNTF9.WKBfI949yiBRcRrit4I0VgJPJ3c8cwKB6fINmrdJBeJKSUcpYA3EPCmpPeuFPZ7VKvOm1YJUfbwIuy5X_Xx3TA

### User Signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### User Signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### Extract the token from the signin response

### Create a Todo
POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New Todo"
}


### Get All Todos
GET {{baseUrl}}/todos
Authorization: Bearer {{token}}

### Get a Todo by ID
GET {{baseUrl}}/todos/1
Authorization: Bearer {{token}}

### Update a Todo
PUT {{baseUrl}}/todos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Update Todo"
}

### Delete a Todo
DELETE {{baseUrl}}/todos/3
Authorization: Bearer {{token}}

### Get All Albums
GET {{baseUrl}}/albums
Authorization: Bearer {{token}}

### Get Album by ID
GET {{baseUrl}}/albums/1
Authorization: Bearer {{token}}

### Create a New Album
POST {{baseUrl}}/albums
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "title": "New Album"
}

### Update an Album
PUT {{baseUrl}}/albums/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "title": "Updated Album Title"
}

### Delete an Album
DELETE {{baseUrl}}/albums/1
Authorization: Bearer {{token}}
```