@baseUrl=http://localhost:8080
// @token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQyNTU2NjM2LCJleHAiOjE3NDI1NjAyMzZ9.ii-giGysL9ttXS_bCcqFjE9ZIbQc72AhihA8WfldOpfImCVPVVH8UvaA5FbaK-vA4fZR6Gxn_Y9Uyrsxpq7jDA

### User Signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### User Signin and store the token
# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}
### Get User Profile Request:
@token = {{login.response.body.*}}

### Extract the token from the signin response

### Get All Todos
GET {{baseUrl}}/todos
Authorization: Bearer {{token}}


### Create a Todo
POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New Todo"
}


### Get a Todo by ID
GET {{baseUrl}}/todos/1
Authorization: Bearer {{token}}

### Update a Todo
PUT {{baseUrl}}/todos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Update Todo"
}

### Delete a Todo
DELETE {{baseUrl}}/todos/3
Authorization: Bearer {{token}}

### Get All Albums
GET {{baseUrl}}/albums
Authorization: Bearer {{token}}

### Get Album by ID
GET {{baseUrl}}/albums/1
Authorization: Bearer {{token}}

### Create a New Album
POST {{baseUrl}}/albums
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "title": "New Album"
}

### Update an Album
PUT {{baseUrl}}/albums/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "title": "Updated Album Title"
}

### Delete an Album
DELETE {{baseUrl}}/albums/1
Authorization: Bearer {{token}}
```